<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="35546" started-at="2021-01-22T13:15:06 EST" finished-at="2021-01-22T13:15:42 EST">
    <groups>
    </groups>
    <test name="HomePage" duration-ms="12140" started-at="2021-01-22T13:15:06 EST" finished-at="2021-01-22T13:15:18 EST">
      <class name="RealProject.RealP.HomePage">
        <test-method status="PASS" signature="startLogin()[pri:0, instance:RealProject.RealP.HomePage@273444fe]" name="startLogin" is-config="true" duration-ms="10" started-at="2021-01-22T13:15:06 EST" finished-at="2021-01-22T13:15:06 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startLogin -->
        <test-method status="PASS" signature="clickLogin()[pri:0, instance:RealProject.RealP.HomePage@273444fe]" name="clickLogin" duration-ms="11463" started-at="2021-01-22T13:15:06 EST" finished-at="2021-01-22T13:15:18 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickLogin -->
        <test-method status="PASS" signature="close()[pri:0, instance:RealProject.RealP.HomePage@273444fe]" name="close" is-config="true" duration-ms="113" started-at="2021-01-22T13:15:18 EST" finished-at="2021-01-22T13:15:18 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- RealProject.RealP.HomePage -->
    </test> <!-- HomePage -->
    <test name="Login" duration-ms="22753" started-at="2021-01-22T13:15:19 EST" finished-at="2021-01-22T13:15:42 EST">
      <class name="RealProject.RealP.LoginPage">
        <test-method status="PASS" signature="startLogin()[pri:0, instance:RealProject.RealP.LoginPage@17fc391b]" name="startLogin" is-config="true" duration-ms="0" started-at="2021-01-22T13:15:19 EST" finished-at="2021-01-22T13:15:19 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startLogin -->
        <test-method status="FAIL" signature="LogIn(java.lang.String, java.lang.String)[pri:0, instance:RealProject.RealP.LoginPage@17fc391b]" name="LogIn" duration-ms="11055" started-at="2021-01-22T13:15:19 EST" data-provider="getData" finished-at="2021-01-22T13:15:30 EST">
          <params>
            <param index="0">
              <value>
                <![CDATA[user1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Header text is matching expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Header text is matching expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at RealProject.RealP.LoginPage.LogIn(LoginPage.java:44)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogIn -->
        <test-method status="FAIL" signature="LogIn(java.lang.String, java.lang.String)[pri:0, instance:RealProject.RealP.LoginPage@17fc391b]" name="LogIn" duration-ms="11365" started-at="2021-01-22T13:15:30 EST" data-provider="getData" finished-at="2021-01-22T13:15:41 EST">
          <params>
            <param index="0">
              <value>
                <![CDATA[user2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password2]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Header text is matching expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Header text is matching expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at RealProject.RealP.LoginPage.LogIn(LoginPage.java:44)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogIn -->
        <test-method status="PASS" signature="close()[pri:0, instance:RealProject.RealP.LoginPage@17fc391b]" name="close" is-config="true" duration-ms="303" started-at="2021-01-22T13:15:41 EST" finished-at="2021-01-22T13:15:42 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- RealProject.RealP.LoginPage -->
    </test> <!-- Login -->
  </suite> <!-- Suite -->
</testng-results>
